FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# 1. Install Base Dependencies & Zephyr Host Tools
# Reference: https://docs.zephyrproject.org/latest/develop/getting_started/index.html#install-host-dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    git cmake ninja-build gperf \
    ccache dfu-util device-tree-compiler wget \
    python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
    make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1 \
    ca-certificates curl \
    gdb-multiarch \
    openocd \
    udev usbutils \
    libusb-1.0-0 libusb-1.0-0-dev \
    libftdi1-2 libftdi1-dev \
    libhidapi-hidraw0 libhidapi-dev \
    libjaylink0 libjaylink-dev \
    locales \
    && rm -rf /var/lib/apt/lists/*

# 2. Set Locale (often required by build tools)
RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# 3. Install Zephyr SDK
# We use the minimal bundle and install only the arm toolchain to save space/time, 
# but you can install 'all' if needed.
ARG ZEPHYR_SDK_VERSION=0.17.4
ARG ZEPHYR_SDK_INSTALL_DIR=/opt/zephyr-sdk
ENV ZEPHYR_SDK_INSTALL_DIR=${ZEPHYR_SDK_INSTALL_DIR}
ENV ZEPHYR_TOOLCHAIN_VARIANT=zephyr

RUN wget -q "https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${ZEPHYR_SDK_VERSION}/zephyr-sdk-${ZEPHYR_SDK_VERSION}_linux-x86_64_minimal.tar.xz" -O /tmp/zephyr-sdk.tar.xz \
    && mkdir -p ${ZEPHYR_SDK_INSTALL_DIR} \
    && tar -xf /tmp/zephyr-sdk.tar.xz -C ${ZEPHYR_SDK_INSTALL_DIR} --strip-components=1 \
    && ${ZEPHYR_SDK_INSTALL_DIR}/setup.sh -t arm-zephyr-eabi -h -c \
    && rm /tmp/zephyr-sdk.tar.xz

# Add Zephyr SDK toolchain to PATH
ENV PATH="${ZEPHYR_SDK_INSTALL_DIR}/arm-zephyr-eabi/bin:${PATH}"

# 4. Install West & Python Dependencies
RUN pip3 install --break-system-packages west

# 5. Setup Zephyr Workspace (Freestanding Setup)
# We initialize a workspace at /opt/zephyrproject so the container has a valid Zephyr instance.
# OPTIMIZATION: We use shallow clones (--depth 1) and remove .git directories to save space.
ENV ZEPHYR_BASE=/opt/zephyrproject/zephyr
RUN west init -m https://github.com/zephyrproject-rtos/zephyr --mr main /opt/zephyrproject \
    && cd /opt/zephyrproject \
    && west update --narrow --fetch-opt=--depth=1 \
    && west zephyr-export \
    && pip3 install --break-system-packages -r /opt/zephyrproject/zephyr/scripts/requirements.txt \
    && find /opt/zephyrproject -name ".git" -type d -exec rm -rf {} +

# 6. Debugging & Tools Setup
# Create udev rules for Black Magic Probe (Note: Host OS must handle actual device mapping)
RUN echo 'SUBSYSTEM=="tty", ATTRS{interface}=="Black Magic GDB Server", SYMLINK+="ttyBmpGdb", MODE="0666"' > /etc/udev/rules.d/99-blackmagic.rules \
    && echo 'SUBSYSTEM=="tty", ATTRS{interface}=="Black Magic UART Port", SYMLINK+="ttyBmpTarg", MODE="0666"' >> /etc/udev/rules.d/99-blackmagic.rules \
    && echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="6018", MODE="0666"' >> /etc/udev/rules.d/99-blackmagic.rules

# GDB Init
RUN mkdir -p /root/.config/gdb \
    && printf 'set auto-load safe-path /\n' > /root/.gdbinit

# Oh My Posh
RUN curl -L https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64 -o /usr/local/bin/oh-my-posh \
    && chmod +x /usr/local/bin/oh-my-posh \
    && printf '\n# oh-my-posh\n%s\n' 'eval "$(oh-my-posh init bash --config robbyrussell)"' >> /etc/bash.bashrc

# 7. Final Configuration
WORKDIR /workspace
CMD ["/bin/bash"]