FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# 1. Install Base Dependencies
# Common build tools for embedded development
RUN apt-get update && apt-get install -y --no-install-recommends \
    git cmake ninja-build gperf \
    ccache dfu-util device-tree-compiler wget \
    python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
    make gcc g++ libsdl2-dev libmagic1 \
    ca-certificates curl \
    gdb-multiarch \
    openocd \
    udev usbutils \
    libusb-1.0-0 libusb-1.0-0-dev \
    libftdi1-2 libftdi1-dev \
    libhidapi-hidraw0 libhidapi-dev \
    libjaylink0 libjaylink-dev \
    locales \
    bzip2 \
    && rm -rf /var/lib/apt/lists/*

# 2. Set Locale
RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# 3. Install GNU Arm Embedded Toolchain
# Version: 14.3.Rel1
ARG ARM_TOOLCHAIN_VERSION=14.3.rel1
ARG ARM_TOOLCHAIN_BASE_URL=https://developer.arm.com/-/media/Files/downloads/gnu/${ARM_TOOLCHAIN_VERSION}/binrel
ARG ARM_TOOLCHAIN_FILENAME=arm-gnu-toolchain-${ARM_TOOLCHAIN_VERSION}-x86_64-arm-none-eabi.tar.xz
ARG INSTALL_DIR=/opt/gcc-arm-none-eabi

RUN wget -q "${ARM_TOOLCHAIN_BASE_URL}/${ARM_TOOLCHAIN_FILENAME}" -O /tmp/gcc-arm.tar.xz \
    && mkdir -p ${INSTALL_DIR} \
    && tar -xf /tmp/gcc-arm.tar.xz -C ${INSTALL_DIR} --strip-components=1 \
    && rm /tmp/gcc-arm.tar.xz

# Add Toolchain to PATH
ENV PATH="${INSTALL_DIR}/bin:${PATH}"

# 4. Debugging & Tools Setup
# Create udev rules for Black Magic Probe
RUN echo 'SUBSYSTEM=="tty", ATTRS{interface}=="Black Magic GDB Server", SYMLINK+="ttyBmpGdb", MODE="0666"' > /etc/udev/rules.d/99-blackmagic.rules \
    && echo 'SUBSYSTEM=="tty", ATTRS{interface}=="Black Magic UART Port", SYMLINK+="ttyBmpTarg", MODE="0666"' >> /etc/udev/rules.d/99-blackmagic.rules \
    && echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="6018", MODE="0666"' >> /etc/udev/rules.d/99-blackmagic.rules

# GDB Init
RUN mkdir -p /root/.config/gdb \
    && printf 'set auto-load safe-path /\n' > /root/.gdbinit

# Oh My Posh
RUN curl -L https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64 -o /usr/local/bin/oh-my-posh \
    && chmod +x /usr/local/bin/oh-my-posh \
    && printf '\n# oh-my-posh\n%s\n' 'eval "$(oh-my-posh init bash --config robbyrussell)"' >> /etc/bash.bashrc

# 5. Final Configuration
WORKDIR /workspace
CMD ["/bin/bash"]
